---

win_ad__domain_name: ad1.d91d.example.opentlc.com

win_users__domain: 'ad1.d91d.example.opentlc.com'
win_users__users:
  - { name: 'james', firstname: 'James', surname: 'Jockey', password: 'redhat@123', state: present }
  - { name: 'bill', firstname: 'Bill', surname: 'Gates', password: 'redhat@123', state: present }
  - { name: 'mickey', firstname: 'Mickey', surname: 'Mouse', password: 'redhat@123', state: present }
  - { name: 'donald', firstname: 'Donald', surname: 'Duck', password: 'redhat@123', state: present }

win_service__services:
  - name: openssh
    params: /SSHServerFeature
    state: latest
    status: started
    start_mode: auto
    service: SSHD
    localport: 22
    protocol: tcp
    firewall_rule: present

