---

- name: install services
  hosts: windows
  gather_facts: yes

  roles:
    - role: win-users
      win_users__domain: 'ad1.3158.example.opentlc.com'
      win_users__users:
        - { name: 'james', firstname: 'James', surname: 'Jockey', password: 'redhat@123', state: present }
        - { name: 'bill', firstname: 'Bill', surname: 'Gates', password: 'redhat@123', state: present }
        - { name: 'mickey', firstname: 'Mickey', surname: 'Mouse', password: 'redhat@123', state: present }
        - { name: 'donald', firstname: 'Donald', surname: 'Duck', password: 'redhat@123', state: present }

