---
# tasks file for roles/win-users

- name: create AD user
  win_domain_user:
   name: "{{ item.name }}"
   firstname: "{{item.firstname }}"
   surname: "{{ item.surname }}"
   password: "{{ item.password }}"
   state: "{{ item.state }}"
   email: "{{ item.name | d(item.firstname | lower + '.' + item.surname | lower) + '@' + win_users__domain }}"
  with_items: "{{ win_users__users }}"

